"""add users table

Revision ID: df29b70d0a87
Revises: e0ffa285f62e
Create Date: 2026-08-28 23:28:58.712641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df29b70d0a87"
down_revision: Union[str, Sequence[str], None] = "e0ffa285f62e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "users",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("password", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.drop_table("links")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "links",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("short_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("original_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column(
      "created_at",
      postgresql.TIMESTAMP(),
      server_default=sa.text("now()"),
      autoincrement=False,
      nullable=False,
    ),
    sa.PrimaryKeyConstraint("id", name=op.f("links_pkey")),
    sa.UniqueConstraint(
      "short_code",
      name=op.f("links_short_code_key"),
      postgresql_include=[],
      postgresql_nulls_not_distinct=False,
    ),
  )
  op.drop_table("users")
  # ### end Alembic commands ###
